- name: install pip3
  apt: name=python3-pip

- name: install lzop
  apt: name=lzop

- name: install libssl-dev
  apt: name=libssl-dev

- name: install libffi-dev
  apt: name=libffi-dev

- name: install wal-e
  pip: name={{ item }}
       executable=pip3
  with_items:
    - wal-e
    - aws
    - azure
    - google
    - swift

- name: install chpst
  apt: name=runit

- name: create /etc/wal-e.d/env
  file: state=directory dest=/etc/wal-e.d/env mode=0750 owner=root group={{ wal_e_postgres_user }}

- name: put /etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY
  template: dest=/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY src=AWS_SECRET_ACCESS_KEY

- name: put /etc/wal-e.d/env/AWS_ACCESS_KEY_ID
  template: dest=/etc/wal-e.d/env/AWS_ACCESS_KEY_ID src=AWS_ACCESS_KEY_ID

- name: put /etc/wal-e.d/env/WALE_S3_PREFIX
  template: dest=/etc/wal-e.d/env/WALE_S3_PREFIX src=WALE_S3_PREFIX

- name: put /etc/wal-e.d/env/WALE_S3_ENDPOINT
  template: dest=/etc/wal-e.d/env/WALE_S3_ENDPOINT src=WALE_S3_ENDPOINT

- name: put /etc/cron.d/wal-e
  template: src=wal-e dest=/etc/cron.d/wal-e
